Feature Text To Speech
biologist79/ESPuino pull request #191
Opened 2023-01-08 15:53 UTC by Joe91

Feature to play around with TTS a little.

- TTS as new playmode (Text from path-line in Webserver)
- TTS as Command with predefined text in Webserver (Settings-Page)
- Commands on Control-Page of Webserver

2023-01-08 19:55 UTC, fschrempf requested changes

2023-01-08 19:55 UTC, fschrempf commented on html/management_EN.html
> +						<option value="179">Schlafe immediately</option>
Sleep

2023-01-08 19:55 UTC, fschrempf commented on html/management_EN.html
> +						<option value="120">Dimm LEDs (nightmode)</option>
Dim

2023-01-08 19:55 UTC, fschrempf commented on html/management_EN.html
> +						<option value="141">Bluetooth Headphoe aktivation / deaktivation </option>
- Missing 'n' in "Headphone"
- 'c' instead of 'k' in "activation/deactivation"
- Maybe "enable/disable" would be even better

2023-01-08 19:55 UTC, fschrempf commented on html/management_EN.html
> +								<option value="141">Bluetooth Headphoe aktivation / deaktivation </option>
See above

2023-02-14 19:27 UTC, Joe91 commented
Seems to work again :-)

2023-03-21 19:23 UTC, Joe91 commented
Shall I separate the command-execution on the control-site of the webserver to a separated PR?
That way you can execute every possible modification directly on the webser without the need to create a Tag or a Button-Combination for it.

2023-04-04 09:09 UTC, biologist79 commented
Will try to test this feature within the upcoming days.

2026-08-13 12:54 UTC, closed without merging